
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

include("maddi-aapi-archive")
include("maddi-aapi-parser")
include("maddi-cst-analysis")
include("maddi-cst-api")
include("maddi-cst-impl")
include("maddi-cst-io")
include("maddi-cst-print")
include("maddi-support")
include("maddi-inspection-api")
include("maddi-inspection-integration")
include("maddi-inspection-parser")
include("maddi-inspection-resource")
include("maddi-graph")
include("maddi-util")
include("maddi-java-parser")
include("maddi-java-bytecode")
include("maddi-modification-common")
include("maddi-modification-io")
include("maddi-modification-linkedvariables")
include("maddi-modification-prepwork")
include("platform")
include("road-to-immutability")
include("maddi-run-config")
include("maddi-gradleplugin")
include("maddi-run-main")
//include("maddi-mvnplugin")
//include("testgradleplugin-analyzer")
//include("testgradleplugin-writeaapi")
//include("testmvnplugin-export")
