
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

//include("aapi-archive")
//include("aapi-parser")
include("cst-analysis")
include("cst-api")
include("cst-impl")
include("cst-io")
include("cst-print")
include("external-support")
//include("inspection-api")
//include("inspection-integration")
//include("inspection-parser")
//include("inspection-resource")
include("internal-graph")
include("internal-util")
//include("java-parser")
//include("java-bytecode")
//include("modification-common")
//include("modification-io")
//include("modification-linkedvariables")
//include("modification-prepwork")
include("platform")
//include("road-to-immutability")
//include("run-config")
//include("run-gradleplugin")
//include("run-main")
//include("run-mvnplugin")
//include("testgradleplugin-analyzer")
//include("testgradleplugin-writeaapi")
//include("testmvnplugin-export")
