package org.e2immu.analyzer.run.openjdkmain;

import ch.qos.logback.classic.Level;
import org.apache.commons.cli.ParseException;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Tag;

/**
 * Guava core (~350k lines, 20k elements): the generics/immutability-depth corpus — recursive self-bounded
 * generics, deep hidden-content structures. Green since 2026-07-17 (certified fixpoint, ~72s at PARALLEL
 * defaults). Config generated by the maddi Maven plugin (see test-oss/maddi-testoss/
 * java_kotlin_refactoring_projects.md); the corpus-root copy carries an absolute workingDirectory.
 */
@Tag("slow")
public class TestGuava {

    @BeforeAll
    public static void beforeAll() {
        ((ch.qos.logback.classic.Logger) LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME)).setLevel(Level.INFO);
        ((ch.qos.logback.classic.Logger) LoggerFactory.getLogger("org.e2immu.analyzer.shallow")).setLevel(Level.DEBUG);
        ((ch.qos.logback.classic.Logger) LoggerFactory
                .getLogger("org.e2immu.analyzer.modification.link.impl.linkgraph.RedundantLinks")).setLevel(Level.ERROR);
    }

    private static final Path CONFIG = TestOssCorpus.config("guava");

    @Test
    public void test() throws IOException, ParseException {
        Assumptions.assumeTrue(Files.exists(CONFIG),
                "requires the guava corpus checkout with its generated input configuration");
        int exitValue = Main.execute(new String[]{
                "--input-configuration=" + CONFIG
                , "--analysis-steps=modification"
                , "--preload-analysis-results-dirs=../maddi-aapi-archive/src/main/resources/org/e2immu/analyzer/aapi/archive/analyzedPackageFiles/jdk"
        });
        assertEquals(Main.EXIT_OK, exitValue);
    }
}
