/*
 * maddi: a modification analyzer for duplication detection and immutability.
 * Copyright 2020-2025, Bart Naudts, https://github.com/CodeLaser/maddi
 *
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free Software
 * Foundation, either version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License for
 * more details. You should have received a copy of the GNU Lesser General Public
 * License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.e2immu.language.cst.api.info;

import org.e2immu.annotation.Fluent;
import org.e2immu.language.cst.api.element.Comment;
import org.e2immu.language.cst.api.element.CompilationUnit;
import org.e2immu.language.cst.api.element.Element;
import org.e2immu.language.cst.api.element.JavaDoc;
import org.e2immu.language.cst.api.expression.AnnotationExpression;
import org.e2immu.language.cst.api.translate.TranslationMap;

import java.util.List;
import java.util.stream.Stream;

/**
 * Base interface for all named, inspectable program elements: types, methods, fields, and parameters.
 * <p>
 * An {@code Info} object progresses through two lifecycle phases, both managed through its
 * {@link Builder}: <em>inspection</em> (structural data populated from source or bytecode,
 * finalised by {@link Builder#commit()}, queried via {@link #hasBeenInspected()}) and
 * <em>analysis</em> (semantic properties attached by the analyser, queried via
 * {@link #hasBeenAnalyzed()}).
 * <p>
 * <b>Identity invariant.</b> Once inspected, an {@code Info} is immutable, and there is exactly one
 * instance per (fully-qualified name, source set): no part of the system should ever hold two distinct
 * {@code Info} objects for the same element. Consequently {@code Info} objects are meant to be compared
 * by identity ({@code ==}). The value-based {@link Object#equals(Object) equals()}/{@code hashCode()}
 * implementations (keyed on fully-qualified name and source set) are a consistency backstop that happens
 * to agree with identity; they are not the contract. Any component that creates {@code Info} objects
 * (a parser, a type loader) is responsible for de-duplicating to a single instance per name and source
 * set.
 */
public interface Info extends Element {

    /**
     * Returns {@code true} once the builder has been committed and all structural data is frozen.
     */
    boolean hasBeenInspected();

    /**
     * Returns a short type-discriminator string ({@code "type"}, {@code "method"},
     * {@code "field"}, {@code "parameter"}, {@code "typeParameter"}, {@code "module"}).
     */
    String info();

    /**
     * Returns the effective visibility of this element.
     */
    Access access();

    /**
     * Returns the compilation unit that directly or transitively owns this element.
     */
    CompilationUnit compilationUnit();

    /**
     * Returns the unqualified name, e.g. {@code "ArrayList"} or {@code "add"}.
     */
    String simpleName();

    /**
     * Returns the fully qualified name, e.g. {@code "java.util.ArrayList"} or
     * {@code "java.util.ArrayList.add(java.lang.Object)"}.
     */
    String fullyQualifiedName();

    /**
     * Returns a unique identifier for this element.
     * <p>
     * Fully qualified names of fields can be misinterpreted; in a codebase spanning multiple source sets,
     * multiple types can have the same fully qualified name, etc. This format allows no ambiguity.
     * <p>
     * Format rules: a {@code ::} prefix carries the source-set name; enclosed types are
     * separated by {@code $} (e.g. {@code a.b.X$Y}); a field is separated from its owner
     * by {@code :}; type parameters are enclosed in {@code []}.
     */
    String descriptor();

    /**
     * Returns {@code true} if this element was generated by the compiler rather than written in source.
     */
    boolean isSynthetic();

    /**
     * Returns the type that directly owns this element.
     * For a {@link TypeInfo} this returns {@code this}.
     */
    TypeInfo typeInfo();

    /**
     * Returns {@code true} once semantic-analysis properties have been attached to this element.
     */
    boolean hasBeenAnalyzed();

    /**
     * Returns the JavaDoc comment attached to this element, or {@code null} if absent.
     */
    JavaDoc javaDoc();

    /**
     * Returns translated copies of this element as described by {@code translationMap}.
     * The list typically contains a single element; it may be empty if the element is dropped by the map.
     */
    List<? extends Info> translate(TranslationMap translationMap);

    /**
     * Builder for constructing and finalising an {@link Info} element during the inspection phase.
     */
    interface Builder<B extends Builder<?>> extends Element.Builder<B> {

        /**
         * Streams the annotations accumulated in the builder so far.
         */
        Stream<AnnotationExpression> annotationStream();

        /**
         * Returns the comments accumulated in the builder so far.
         */
        List<Comment> comments();

        /**
         * Sets the visibility of the element being built.
         */
        @Fluent
        B setAccess(Access access);

        /**
         * Replaces the annotation at the given index.
         */
        @Fluent
        B setAnnotationExpression(int index, AnnotationExpression annotationExpression);

        /**
         * Returns the annotation whose type has the given fully qualified name,
         * or {@code null} if no such annotation is present.
         */
        AnnotationExpression haveAnnotation(String fullyQualifiedName);

        /**
         * Marks the element as compiler-generated ({@link Info#isSynthetic()} will return {@code true}).
         */
        @Fluent
        B setSynthetic(boolean synthetic);

        /**
         * Returns {@code true} if {@link #commit()} has already been called.
         */
        boolean hasBeenCommitted();

        /**
         * Derives and sets the effective access level from the accumulated modifiers.
         * Call this once all modifier-setting calls are done, before {@link #commit()}.
         */
        @Fluent
        B computeAccess();

        /**
         * Attaches a JavaDoc comment to the element being built.
         */
        @Fluent
        B setJavaDoc(JavaDoc javaDoc);

        /**
         * Finalises inspection, freezing all structural data.
         * After this call {@link Info#hasBeenInspected()} returns {@code true}.
         */
        void commit();
    }

}
